version: '3'
services:
    mysqldb:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - TZ=Asia/Hong_Kong
            - MYSQL_ROOT_PASSWORD=example
            - MYSQL_USER=example
            - MYSQL_PASSWORD=example
            - MYSQL_DATABASE=example
        ports:
            - '3306:3306'
        volumes: 
            - type: bind
              source: ./dist/db-schema.sql
              target: /docker-entrypoint-initdb.d/db-schema.sql
    adminer:
        image: adminer
        ports:
            - '9000:8080'
        environment:
            - TZ=Asia/Hong_Kong
            - ADMINER_DEFAULT_SERVER=mysqldb
